version: "3.8"

services:
    app:
        build: .
        container_name: kasku-app
        volumes:
            - .:/var/www
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:alpine
        container_name: kasku-nginx
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        expose:
            - "80"
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: kasku-mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

    redis:
        image: redis:latest
        container_name: kasku-redis
        ports:
            - "6379:6379"

volumes:
    dbdata:
